runtime: nodejs14
env: standard

instance_class: F1


handlers:
  - url: /
    static_files: public/index.html
    upload: public/index.html

  - url: /public/static/(.*)
    static_files: public/static/\1
    upload: public/static/(.*)

  - url: /(.*)
    static_files: public/\1
    upload: public/(.*)
